- name: create supervisor configuration
  template: src=supervisord.conf dest=/etc/supervisord.conf owner=root group=root mode=0644
  notify: restart supervisor

- name: add cron job to insure that supervisor is running
  cron: name="make sure supervisor is running" minute="*" user="root" job="ps -deaf | grep supervisord | grep -v grep || {{supervisord_binary}}"
